adding conditional, if no nbs are failing, everything is fine if there is some failing, then the build should fail.

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -72,4 +72,12 @@ build_script:
               done
           fi
         done
-  - echo "The failing notebooks are ${list_of_failing_nbs[@]}"
+    - if [[ ${#list_of_failing_nbs[@]} -eq 0 ]]; then
+        echo "Hurray! No jupyter notebooks are failing!"
+      fi
+    - if [[ ${#list_of_failing_nbs[@]} -gt 0 ]]; then
+        echo "The failing notebooks are ${list_of_failing_nbs[@]}, exiting with error.";
+        exit 1;
+      fi
+
+
